### ISSUE TITLE
Test case writing and Testing Issuance portal functionalities

### ISSUE THREAD

**Issue by Pritzz4** [Sunbird-RC/community#659]
- [ ] Issuing VC by Adding Bulk Record - #203 
- [ ] Mask contact number in the contact number - #620 
- [ ] VC list view dynamic columns - #595 
- [ ] Issuer > VC template edit > adavance editor - #415
