### ISSUE TITLE
[C4GT] Admin Portal to Build Registry and Credentialing Platform

### ISSUE THREAD

**Issue by jayadinni** [Sunbird-RC/community#666]
### Project Details
<hr>
Admin Portal to help build Registry & Credentialing platform easily through front end. This portal will use Sunbird RC framework. The objective is for any person (generally system administrators) trying to create a registry should be able to configure it easily through the admin portal. The admin portal leverages the Sunbird RC APIs and provides basic functionality such as create entity schema, add a record, and so on.

### Learning Path

1. https://github.com/orgs/Sunbird-RC/discussions/676
2. Sunbird RC documentation: https://docs.sunbirdrc.dev/learn/readme
3. Essential reading
   1. https://docs.sunbirdrc.dev/learn/electronic-registries
   2. https://docs.sunbirdrc.dev/learn/electronic-registries/registry-vs-database

**Complexity**: Medium

**Skills Required**
1. Angular
5. Typescript
6. Postman API

**Name of Mentors**
1. Tejash L
3. Chaitrali

**Project size**
~8 weeks

**Project Set Up**
https://docs.sunbirdrc.dev/developer-documentation/admin-portal

### Features to be implemented (Acceptance criteria)
<hr>

1. **Creation of Registry Schema**
- [x] #668
- [ ] UI to define attributes of schema and configure properties (mandatory, Part of column in the listing, etc)
- [ ] Use Sample Schema and edit it

**Publish**
- [ ] Publish schema 

**Dashboard**
- [ ] View Schemas published or unpublished, to explore respective APIs

**Roles Management**
Currently, user needs to create roles in Keycloak. In this feature, user should be allowed to create and manage roles from admin portal.
- [ ] Creating Roles

**Add records**
For the Schema created, the user should be able to view and add records.
- [ ] Listing
- [ ] Add Single
- [ ] Bulk Records

**Ownership**
- [ ] Configure authentication type
- [ ] Configure

**Attestation Workflow**
Admin should be able to configure attestation workflow
- [ ] Configure Auto attestation
- [ ] Configure Attestor
- [ ] Configure attributes required for attestation  

**Verifiable credential Template**
Configure Verifiable Credential (VC) for the schema defined
- [ ] View and Use Existing Template
- [ ] Edit Template
- [ ] Upload SVG Template
- [ ] Create Custom Template

### Milestones
1. Create and review high-level tech design
2. Implement acceptance criteria # 1

### Design
https://www.figma.com/file/dRmU5ODkJDuZgvuMZQRTvQ/Admin-Portal?type=design&node-id=3010-14743&t=0aqpeHOk7pFVRc7l-4

**Comment by Mohit-Aasirwal** [comment]
Is it the necessity of the portal to be built with Angular or is it flexible in terms of framework.
I've pretty much experience of developing scalable and responsive NextJS frontends so curious if this can be possible.
btw the project looks good to be done.
