### ISSUE TITLE
Sunbird-RC 2.x

### ISSUE THREAD

**Issue by manukalia29** [Sunbird-RC/community#887]
Tasks identified for integration as of now -
- [ ] [Create a schema to store did of issuers `Issuer`; Create a service to generate and save, resolve did, resolve issuer did by name, `IDService`](https://github.com/Sunbird-RC/community/issues/919)
- [ ] [Create a service to extract and save the credentials schema `CredentialSchemaService`](https://github.com/Sunbird-RC/community/issues/920)
- [ ] [Create a proxy service to issue credential, retrieve, revoke and verify a credential `CredentialService`](https://github.com/Sunbird-RC/community/issues/921)
- [ ] [Write unique tests for all the services created ensuring all the changes](https://github.com/Sunbird-RC/community/issues/922)
- [ ] [registry-cli, docker-compose should have all the changes reflected](https://github.com/Sunbird-RC/community/issues/923)

**Comment by holashchand** [comment]
Tasks identified for integration as of now -
- [ ] [Create a schema to store did of issuers `Issuer`; Create a service to generate and save, resolve did, resolve issuer did by name, `IDService`](https://github.com/Sunbird-RC/community/issues/919)
- [ ] [Create a service to extract and save the credentials schema `CredentialSchemaService`](https://github.com/Sunbird-RC/community/issues/920)
- [ ] [Create a proxy service to issue credential, retrieve, revoke and verify a credential `CredentialService`](https://github.com/Sunbird-RC/community/issues/921)
- [ ] [Write unique tests for all the services created ensuring all the changes](https://github.com/Sunbird-RC/community/issues/922)
- [ ] [registry-cli, docker-compose should have all the changes reflected](https://github.com/Sunbird-RC/community/issues/923)
