### ISSUE TITLE
[FEAT]: Publish custom context based on Credential Schema Template

### ISSUE THREAD

**Issue by srprasanna** [Sunbird-RC/community#892]
### What is the feature request for?

Registry Core

### What problem/inconvenience (if any) will this feature solve?

Currently all contexts point to the default VC spec published by W3C. Whenever someone creates a new Credential Schema, we should generate a context out of this and make this publicly available. The URL should be referenced within the VC as a Context URL as well. This URL should also be used for validating the Payload before generating the VC. 

Sub tickets to be created for this EPIC.

- [ ] Change should be compatible with 1.x
- [ ] Change should be compatible with 2.x
- [ ] Should be part of Context-Proxy Service

### Describe the feature clearly.

Add a new feature that does ....

**Comment by srprasanna** [comment]
Based on discussions with the team, this can be a globally available context. This can be published anywhere not necessarily within  our system.
