### ISSUE TITLE
[FEAT]: Deep dive on AWS CDK

### ISSUE THREAD

**Issue by srprasanna** [Sunbird-RC/community#893]
### What is the feature request for?

Registry Core

### What problem/inconvenience (if any) will this feature solve?

At the end of this exercise we should:

- [ ] Have a full understanding of the CDK to maintain and update further
- [ ] Document how to use the CDK to be published on our microsite
- [ ] Validate configuration Options and document them
- [ ] Identify missing pieces to prepare the future roadmap.
- [ ] Ensure that the CDK is generic and complies with both LTS versions 1.x and 2.x

### Describe the feature clearly.

Add a new feature that does ....
