### ISSUE TITLE
[FEAT]: Create easy deployment kit for AWS

### ISSUE THREAD

**Issue by srprasanna** [Sunbird-RC/community#911]
### What is the feature request for?

Other

### What problem/inconvenience (if any) will this feature solve?

At present we have a CDK for Sunbird-RC 1.0, we want to extend it to deploy 2.0 services as well. This will include the following:

- [ ] Understand existing CDK
- [ ] Create community discussion to decide on features
- [ ] Extend existing CDK for 2.x
- [ ] Document deployment steps

### Describe the feature clearly.

Add a new feature that does ....
