### ISSUE TITLE
[FEAT]: Create easy deployment kit for GCP

### ISSUE THREAD

**Issue by srprasanna** [Sunbird-RC/community#913]
### What is the feature request for?

Other

### What problem/inconvenience (if any) will this feature solve?

Create a cloud deployer for GCP. This will include the following:
- [ ] Create community discussion to decide on features
- [ ] Implement deployment kit for 2.x
- [ ] Document deployment steps

### Describe the feature clearly.

Add a new feature that does ....
